# https://aka.ms/yaml

pool:
  vmImage: vs2017-win2016

trigger:
  branches:
    include:
      - source
    exclude:
      - master
  paths:
    exclude:
      - .gitignore
      - README.md

steps:
  - task: cake-build.cake.cake-build-task.Cake@0
    displayName: "Build and publish Wyam site"
    inputs:
      target: Deploy
    env:
      GITHUB_ACCESS_TOKEN: $(githubAccessToken)
      GITHUB_USERNAME: "heebinho"